server {
    listen 80 ;

    gzip on;
    access_log /var/log/nginx/mediacms.io.access.log;

    error_log  /var/log/nginx/mediacms.io.error.log  warn;

    location /static {
        alias /home/mediacms.io/mediacms/static ;
    }

    location /media/original {
        alias /home/mediacms.io/mediacms/media_files/original;
    }

    location /media {
        alias /home/mediacms.io/mediacms/media_files ;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
    }

    # Proxy EmbeddedCallWidget API requests.
    location /proxy.shenyin.eu/proxy/api/ {
        proxy_ssl_server_name on;
        proxy_set_header Host proxy.shenyin.eu;
        proxy_set_header X-Embedded-Call-Access-Token "g8HhqB-KG8PrJyu43ww5retMWYiyEdcG";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass https://proxy.shenyin.eu/proxy/api/;
    }

    # Proxy EmbeddedCallWidget SDK static requests.
    location /proxy.shenyin.eu/proxy/sdk/ {
        proxy_ssl_server_name on;
        proxy_set_header Host proxy.shenyin.eu;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass https://proxy.shenyin.eu/proxy/sdk/;
    }

    # Proxy EmbeddedCallWidget websocket requests.
    location /proxy.shenyin.eu/proxy/ws/ {
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host proxy.shenyin.eu;
        proxy_set_header X-Embedded-Call-Access-Token "g8HhqB-KG8PrJyu43ww5retMWYiyEdcG";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600;
        proxy_pass https://proxy.shenyin.eu/proxy/ws/;
    }

    location / {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

        include /etc/nginx/sites-enabled/uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;
    }
}
