# Generated by Django 4.2.2 on 2025-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantuiApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='三退者名称')),
                ('content', models.TextField(verbose_name='申请内容')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '三退申请',
                'verbose_name_plural': '三退申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
