# Generated by Django 4.2.2 on 2025-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_santuiapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='santuiapplication',
            name='ticket',
            field=models.TextField(blank=True, null=True, verbose_name='三退号码'),
        ),
    ]
